import { Inter } from 'next/font/google'
import Document, { Html, Head, Main, NextScript } from 'next/document';
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Isabelle Kwan',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta charSet="UTF-8" />
      </Head>
      <body className={inter.className}>{children}</body>
    </html>
  )
}
